### ISSUE TITLE
MAPA_MENTAL

### ISSUE THREAD

**Issue by Victor-noe12** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Victor-noe12#2]
[Mapa Mental_dis.pdf](https://github.com/user-attachments/files/17091142/Mapa.Mental_dis.pdf)

**Comment by LenninGS-0** [comment]
Exposición de Ideas Centrales:5/5
Redacción y Ortografía:5/5
Presentación visual:5/5
Referencias:5/5
Calificación Final:20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
